//#pragma warning disable 1591
////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:4.0.30319.42000
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace BusesWorkshop.DAL
//{
//	using System.Data.Linq;
//	using System.Data.Linq.Mapping;
//	using System.Data;
//	using System.Collections.Generic;
//	using System.Reflection;
//	using System.Linq;
//	using System.Linq.Expressions;
//	using System.ComponentModel;
//	using System;
	
	
//	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HR_sales")]
//	public partial class HrDataContext : System.Data.Linq.DataContext
//	{
		
//		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
//    #region Extensibility Method Definitions
//    partial void OnCreated();
//    partial void InsertBranchy(Branchy instance);
//    partial void UpdateBranchy(Branchy instance);
//    partial void DeleteBranchy(Branchy instance);
//    partial void InsertSection(Section instance);
//    partial void UpdateSection(Section instance);
//    partial void DeleteSection(Section instance);
//    partial void InsertUserSection(UserSection instance);
//    partial void UpdateUserSection(UserSection instance);
//    partial void DeleteUserSection(UserSection instance);
//    partial void InsertUser(User instance);
//    partial void UpdateUser(User instance);
//    partial void DeleteUser(User instance);
//    #endregion
		
//		public HrDataContext() : 
//				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HR_salesConnectionString1"].ConnectionString, mappingSource)
//		{
//			OnCreated();
//		}
		
//		public HrDataContext(string connection) : 
//				base(connection, mappingSource)
//		{
//			OnCreated();
//		}
		
//		public HrDataContext(System.Data.IDbConnection connection) : 
//				base(connection, mappingSource)
//		{
//			OnCreated();
//		}
		
//		public HrDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
//				base(connection, mappingSource)
//		{
//			OnCreated();
//		}
		
//		public HrDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
//				base(connection, mappingSource)
//		{
//			OnCreated();
//		}
		
//		public System.Data.Linq.Table<Branchy> Branchies
//		{
//			get
//			{
//				return this.GetTable<Branchy>();
//			}
//		}
		
//		public System.Data.Linq.Table<Section> Sections
//		{
//			get
//			{
//				return this.GetTable<Section>();
//			}
//		}
		
//		public System.Data.Linq.Table<UserSection> UserSections
//		{
//			get
//			{
//				return this.GetTable<UserSection>();
//			}
//		}
		
//		public System.Data.Linq.Table<User> Users
//		{
//			get
//			{
//				return this.GetTable<User>();
//			}
//		}
//	}
	
//	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Branchies")]
//	public partial class Branchy : INotifyPropertyChanging, INotifyPropertyChanged
//	{
		
//		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
//		private int _ID;
		
//		private string _BranchName;
		
//		private int _CompanyID;
		
//		private System.Nullable<int> _BranchManager;
		
//		private System.Nullable<int> _FinancialManager;
		
//		private System.Nullable<int> _HRManager;
		
//		private System.Nullable<int> _ManagerialManager;
		
//		private System.Nullable<int> _ExecutiveManager;
		
//		private System.Nullable<int> _ExcManagerAssist;
		
//		private System.Nullable<int> _RealEstateComID;
		
//		private System.Nullable<int> _ParentID;
		
//		private string _BranchAdress;
		
//		private System.Data.Linq.Binary _BranchLogo;
		
//		private string _BranchPhone1;
		
//		private string _BranchPhone2;
		
//		private string _BranchPhone3;
		
//		private string _BranchMobile1;
		
//		private string _BranchMobile2;
		
//		private string _BranchMobile3;
		
//		private string _ReponsiblePersonMobile;
		
//		private string _BranchFax;
		
//		private string _BranchEmail1;
		
//		private string _BranchEmail2;
		
//		private string _BranchEmail3;
		
//		private bool _IsActive;
		
//		private System.Nullable<int> _EmployeesCapacity;
		
//		private System.Nullable<int> _Test;
		
//		private EntitySet<Branchy> _Branchies;
		
//		private EntitySet<UserSection> _UserSections;
		
//		private EntitySet<User> _Users;
		
//		private EntityRef<Branchy> _Branchy1;
		
//    #region Extensibility Method Definitions
//    partial void OnLoaded();
//    partial void OnValidate(System.Data.Linq.ChangeAction action);
//    partial void OnCreated();
//    partial void OnIDChanging(int value);
//    partial void OnIDChanged();
//    partial void OnBranchNameChanging(string value);
//    partial void OnBranchNameChanged();
//    partial void OnCompanyIDChanging(int value);
//    partial void OnCompanyIDChanged();
//    partial void OnBranchManagerChanging(System.Nullable<int> value);
//    partial void OnBranchManagerChanged();
//    partial void OnFinancialManagerChanging(System.Nullable<int> value);
//    partial void OnFinancialManagerChanged();
//    partial void OnHRManagerChanging(System.Nullable<int> value);
//    partial void OnHRManagerChanged();
//    partial void OnManagerialManagerChanging(System.Nullable<int> value);
//    partial void OnManagerialManagerChanged();
//    partial void OnExecutiveManagerChanging(System.Nullable<int> value);
//    partial void OnExecutiveManagerChanged();
//    partial void OnExcManagerAssistChanging(System.Nullable<int> value);
//    partial void OnExcManagerAssistChanged();
//    partial void OnRealEstateComIDChanging(System.Nullable<int> value);
//    partial void OnRealEstateComIDChanged();
//    partial void OnParentIDChanging(System.Nullable<int> value);
//    partial void OnParentIDChanged();
//    partial void OnBranchAdressChanging(string value);
//    partial void OnBranchAdressChanged();
//    partial void OnBranchLogoChanging(System.Data.Linq.Binary value);
//    partial void OnBranchLogoChanged();
//    partial void OnBranchPhone1Changing(string value);
//    partial void OnBranchPhone1Changed();
//    partial void OnBranchPhone2Changing(string value);
//    partial void OnBranchPhone2Changed();
//    partial void OnBranchPhone3Changing(string value);
//    partial void OnBranchPhone3Changed();
//    partial void OnBranchMobile1Changing(string value);
//    partial void OnBranchMobile1Changed();
//    partial void OnBranchMobile2Changing(string value);
//    partial void OnBranchMobile2Changed();
//    partial void OnBranchMobile3Changing(string value);
//    partial void OnBranchMobile3Changed();
//    partial void OnReponsiblePersonMobileChanging(string value);
//    partial void OnReponsiblePersonMobileChanged();
//    partial void OnBranchFaxChanging(string value);
//    partial void OnBranchFaxChanged();
//    partial void OnBranchEmail1Changing(string value);
//    partial void OnBranchEmail1Changed();
//    partial void OnBranchEmail2Changing(string value);
//    partial void OnBranchEmail2Changed();
//    partial void OnBranchEmail3Changing(string value);
//    partial void OnBranchEmail3Changed();
//    partial void OnIsActiveChanging(bool value);
//    partial void OnIsActiveChanged();
//    partial void OnEmployeesCapacityChanging(System.Nullable<int> value);
//    partial void OnEmployeesCapacityChanged();
//    partial void OnTestChanging(System.Nullable<int> value);
//    partial void OnTestChanged();
//    #endregion
		
//		public Branchy()
//		{
//			this._Branchies = new EntitySet<Branchy>(new Action<Branchy>(this.attach_Branchies), new Action<Branchy>(this.detach_Branchies));
//			this._UserSections = new EntitySet<UserSection>(new Action<UserSection>(this.attach_UserSections), new Action<UserSection>(this.detach_UserSections));
//			this._Users = new EntitySet<User>(new Action<User>(this.attach_Users), new Action<User>(this.detach_Users));
//			this._Branchy1 = default(EntityRef<Branchy>);
//			OnCreated();
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
//		public int ID
//		{
//			get
//			{
//				return this._ID;
//			}
//			set
//			{
//				if ((this._ID != value))
//				{
//					this.OnIDChanging(value);
//					this.SendPropertyChanging();
//					this._ID = value;
//					this.SendPropertyChanged("ID");
//					this.OnIDChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
//		public string BranchName
//		{
//			get
//			{
//				return this._BranchName;
//			}
//			set
//			{
//				if ((this._BranchName != value))
//				{
//					this.OnBranchNameChanging(value);
//					this.SendPropertyChanging();
//					this._BranchName = value;
//					this.SendPropertyChanged("BranchName");
//					this.OnBranchNameChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="Int NOT NULL")]
//		public int CompanyID
//		{
//			get
//			{
//				return this._CompanyID;
//			}
//			set
//			{
//				if ((this._CompanyID != value))
//				{
//					this.OnCompanyIDChanging(value);
//					this.SendPropertyChanging();
//					this._CompanyID = value;
//					this.SendPropertyChanged("CompanyID");
//					this.OnCompanyIDChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchManager", DbType="Int")]
//		public System.Nullable<int> BranchManager
//		{
//			get
//			{
//				return this._BranchManager;
//			}
//			set
//			{
//				if ((this._BranchManager != value))
//				{
//					this.OnBranchManagerChanging(value);
//					this.SendPropertyChanging();
//					this._BranchManager = value;
//					this.SendPropertyChanged("BranchManager");
//					this.OnBranchManagerChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinancialManager", DbType="Int")]
//		public System.Nullable<int> FinancialManager
//		{
//			get
//			{
//				return this._FinancialManager;
//			}
//			set
//			{
//				if ((this._FinancialManager != value))
//				{
//					this.OnFinancialManagerChanging(value);
//					this.SendPropertyChanging();
//					this._FinancialManager = value;
//					this.SendPropertyChanged("FinancialManager");
//					this.OnFinancialManagerChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HRManager", DbType="Int")]
//		public System.Nullable<int> HRManager
//		{
//			get
//			{
//				return this._HRManager;
//			}
//			set
//			{
//				if ((this._HRManager != value))
//				{
//					this.OnHRManagerChanging(value);
//					this.SendPropertyChanging();
//					this._HRManager = value;
//					this.SendPropertyChanged("HRManager");
//					this.OnHRManagerChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagerialManager", DbType="Int")]
//		public System.Nullable<int> ManagerialManager
//		{
//			get
//			{
//				return this._ManagerialManager;
//			}
//			set
//			{
//				if ((this._ManagerialManager != value))
//				{
//					this.OnManagerialManagerChanging(value);
//					this.SendPropertyChanging();
//					this._ManagerialManager = value;
//					this.SendPropertyChanged("ManagerialManager");
//					this.OnManagerialManagerChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExecutiveManager", DbType="Int")]
//		public System.Nullable<int> ExecutiveManager
//		{
//			get
//			{
//				return this._ExecutiveManager;
//			}
//			set
//			{
//				if ((this._ExecutiveManager != value))
//				{
//					this.OnExecutiveManagerChanging(value);
//					this.SendPropertyChanging();
//					this._ExecutiveManager = value;
//					this.SendPropertyChanged("ExecutiveManager");
//					this.OnExecutiveManagerChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExcManagerAssist", DbType="Int")]
//		public System.Nullable<int> ExcManagerAssist
//		{
//			get
//			{
//				return this._ExcManagerAssist;
//			}
//			set
//			{
//				if ((this._ExcManagerAssist != value))
//				{
//					this.OnExcManagerAssistChanging(value);
//					this.SendPropertyChanging();
//					this._ExcManagerAssist = value;
//					this.SendPropertyChanged("ExcManagerAssist");
//					this.OnExcManagerAssistChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealEstateComID", DbType="Int")]
//		public System.Nullable<int> RealEstateComID
//		{
//			get
//			{
//				return this._RealEstateComID;
//			}
//			set
//			{
//				if ((this._RealEstateComID != value))
//				{
//					this.OnRealEstateComIDChanging(value);
//					this.SendPropertyChanging();
//					this._RealEstateComID = value;
//					this.SendPropertyChanged("RealEstateComID");
//					this.OnRealEstateComIDChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="Int")]
//		public System.Nullable<int> ParentID
//		{
//			get
//			{
//				return this._ParentID;
//			}
//			set
//			{
//				if ((this._ParentID != value))
//				{
//					if (this._Branchy1.HasLoadedOrAssignedValue)
//					{
//						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
//					}
//					this.OnParentIDChanging(value);
//					this.SendPropertyChanging();
//					this._ParentID = value;
//					this.SendPropertyChanged("ParentID");
//					this.OnParentIDChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchAdress", DbType="NVarChar(MAX)")]
//		public string BranchAdress
//		{
//			get
//			{
//				return this._BranchAdress;
//			}
//			set
//			{
//				if ((this._BranchAdress != value))
//				{
//					this.OnBranchAdressChanging(value);
//					this.SendPropertyChanging();
//					this._BranchAdress = value;
//					this.SendPropertyChanged("BranchAdress");
//					this.OnBranchAdressChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchLogo", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
//		public System.Data.Linq.Binary BranchLogo
//		{
//			get
//			{
//				return this._BranchLogo;
//			}
//			set
//			{
//				if ((this._BranchLogo != value))
//				{
//					this.OnBranchLogoChanging(value);
//					this.SendPropertyChanging();
//					this._BranchLogo = value;
//					this.SendPropertyChanged("BranchLogo");
//					this.OnBranchLogoChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchPhone1", DbType="NVarChar(30)")]
//		public string BranchPhone1
//		{
//			get
//			{
//				return this._BranchPhone1;
//			}
//			set
//			{
//				if ((this._BranchPhone1 != value))
//				{
//					this.OnBranchPhone1Changing(value);
//					this.SendPropertyChanging();
//					this._BranchPhone1 = value;
//					this.SendPropertyChanged("BranchPhone1");
//					this.OnBranchPhone1Changed();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchPhone2", DbType="NVarChar(30)")]
//		public string BranchPhone2
//		{
//			get
//			{
//				return this._BranchPhone2;
//			}
//			set
//			{
//				if ((this._BranchPhone2 != value))
//				{
//					this.OnBranchPhone2Changing(value);
//					this.SendPropertyChanging();
//					this._BranchPhone2 = value;
//					this.SendPropertyChanged("BranchPhone2");
//					this.OnBranchPhone2Changed();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchPhone3", DbType="NVarChar(30)")]
//		public string BranchPhone3
//		{
//			get
//			{
//				return this._BranchPhone3;
//			}
//			set
//			{
//				if ((this._BranchPhone3 != value))
//				{
//					this.OnBranchPhone3Changing(value);
//					this.SendPropertyChanging();
//					this._BranchPhone3 = value;
//					this.SendPropertyChanged("BranchPhone3");
//					this.OnBranchPhone3Changed();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchMobile1", DbType="NVarChar(30)")]
//		public string BranchMobile1
//		{
//			get
//			{
//				return this._BranchMobile1;
//			}
//			set
//			{
//				if ((this._BranchMobile1 != value))
//				{
//					this.OnBranchMobile1Changing(value);
//					this.SendPropertyChanging();
//					this._BranchMobile1 = value;
//					this.SendPropertyChanged("BranchMobile1");
//					this.OnBranchMobile1Changed();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchMobile2", DbType="NVarChar(30)")]
//		public string BranchMobile2
//		{
//			get
//			{
//				return this._BranchMobile2;
//			}
//			set
//			{
//				if ((this._BranchMobile2 != value))
//				{
//					this.OnBranchMobile2Changing(value);
//					this.SendPropertyChanging();
//					this._BranchMobile2 = value;
//					this.SendPropertyChanged("BranchMobile2");
//					this.OnBranchMobile2Changed();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchMobile3", DbType="NVarChar(30)")]
//		public string BranchMobile3
//		{
//			get
//			{
//				return this._BranchMobile3;
//			}
//			set
//			{
//				if ((this._BranchMobile3 != value))
//				{
//					this.OnBranchMobile3Changing(value);
//					this.SendPropertyChanging();
//					this._BranchMobile3 = value;
//					this.SendPropertyChanged("BranchMobile3");
//					this.OnBranchMobile3Changed();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReponsiblePersonMobile", DbType="NVarChar(30)")]
//		public string ReponsiblePersonMobile
//		{
//			get
//			{
//				return this._ReponsiblePersonMobile;
//			}
//			set
//			{
//				if ((this._ReponsiblePersonMobile != value))
//				{
//					this.OnReponsiblePersonMobileChanging(value);
//					this.SendPropertyChanging();
//					this._ReponsiblePersonMobile = value;
//					this.SendPropertyChanged("ReponsiblePersonMobile");
//					this.OnReponsiblePersonMobileChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchFax", DbType="NVarChar(30)")]
//		public string BranchFax
//		{
//			get
//			{
//				return this._BranchFax;
//			}
//			set
//			{
//				if ((this._BranchFax != value))
//				{
//					this.OnBranchFaxChanging(value);
//					this.SendPropertyChanging();
//					this._BranchFax = value;
//					this.SendPropertyChanged("BranchFax");
//					this.OnBranchFaxChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchEmail1", DbType="NVarChar(80)")]
//		public string BranchEmail1
//		{
//			get
//			{
//				return this._BranchEmail1;
//			}
//			set
//			{
//				if ((this._BranchEmail1 != value))
//				{
//					this.OnBranchEmail1Changing(value);
//					this.SendPropertyChanging();
//					this._BranchEmail1 = value;
//					this.SendPropertyChanged("BranchEmail1");
//					this.OnBranchEmail1Changed();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchEmail2", DbType="NVarChar(80)")]
//		public string BranchEmail2
//		{
//			get
//			{
//				return this._BranchEmail2;
//			}
//			set
//			{
//				if ((this._BranchEmail2 != value))
//				{
//					this.OnBranchEmail2Changing(value);
//					this.SendPropertyChanging();
//					this._BranchEmail2 = value;
//					this.SendPropertyChanged("BranchEmail2");
//					this.OnBranchEmail2Changed();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchEmail3", DbType="NVarChar(80)")]
//		public string BranchEmail3
//		{
//			get
//			{
//				return this._BranchEmail3;
//			}
//			set
//			{
//				if ((this._BranchEmail3 != value))
//				{
//					this.OnBranchEmail3Changing(value);
//					this.SendPropertyChanging();
//					this._BranchEmail3 = value;
//					this.SendPropertyChanged("BranchEmail3");
//					this.OnBranchEmail3Changed();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
//		public bool IsActive
//		{
//			get
//			{
//				return this._IsActive;
//			}
//			set
//			{
//				if ((this._IsActive != value))
//				{
//					this.OnIsActiveChanging(value);
//					this.SendPropertyChanging();
//					this._IsActive = value;
//					this.SendPropertyChanged("IsActive");
//					this.OnIsActiveChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeesCapacity", DbType="Int")]
//		public System.Nullable<int> EmployeesCapacity
//		{
//			get
//			{
//				return this._EmployeesCapacity;
//			}
//			set
//			{
//				if ((this._EmployeesCapacity != value))
//				{
//					this.OnEmployeesCapacityChanging(value);
//					this.SendPropertyChanging();
//					this._EmployeesCapacity = value;
//					this.SendPropertyChanged("EmployeesCapacity");
//					this.OnEmployeesCapacityChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Test", DbType="Int")]
//		public System.Nullable<int> Test
//		{
//			get
//			{
//				return this._Test;
//			}
//			set
//			{
//				if ((this._Test != value))
//				{
//					this.OnTestChanging(value);
//					this.SendPropertyChanging();
//					this._Test = value;
//					this.SendPropertyChanged("Test");
//					this.OnTestChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Branchy_Branchy", Storage="_Branchies", ThisKey="ID", OtherKey="ParentID")]
//		public EntitySet<Branchy> Branchies
//		{
//			get
//			{
//				return this._Branchies;
//			}
//			set
//			{
//				this._Branchies.Assign(value);
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Branchy_UserSection", Storage="_UserSections", ThisKey="ID", OtherKey="BranchID")]
//		public EntitySet<UserSection> UserSections
//		{
//			get
//			{
//				return this._UserSections;
//			}
//			set
//			{
//				this._UserSections.Assign(value);
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Branchy_User", Storage="_Users", ThisKey="ID", OtherKey="BranchID")]
//		public EntitySet<User> Users
//		{
//			get
//			{
//				return this._Users;
//			}
//			set
//			{
//				this._Users.Assign(value);
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Branchy_Branchy", Storage="_Branchy1", ThisKey="ParentID", OtherKey="ID", IsForeignKey=true)]
//		public Branchy Branchy1
//		{
//			get
//			{
//				return this._Branchy1.Entity;
//			}
//			set
//			{
//				Branchy previousValue = this._Branchy1.Entity;
//				if (((previousValue != value) 
//							|| (this._Branchy1.HasLoadedOrAssignedValue == false)))
//				{
//					this.SendPropertyChanging();
//					if ((previousValue != null))
//					{
//						this._Branchy1.Entity = null;
//						previousValue.Branchies.Remove(this);
//					}
//					this._Branchy1.Entity = value;
//					if ((value != null))
//					{
//						value.Branchies.Add(this);
//						this._ParentID = value.ID;
//					}
//					else
//					{
//						this._ParentID = default(Nullable<int>);
//					}
//					this.SendPropertyChanged("Branchy1");
//				}
//			}
//		}
		
//		public event PropertyChangingEventHandler PropertyChanging;
		
//		public event PropertyChangedEventHandler PropertyChanged;
		
//		protected virtual void SendPropertyChanging()
//		{
//			if ((this.PropertyChanging != null))
//			{
//				this.PropertyChanging(this, emptyChangingEventArgs);
//			}
//		}
		
//		protected virtual void SendPropertyChanged(String propertyName)
//		{
//			if ((this.PropertyChanged != null))
//			{
//				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
//			}
//		}
		
//		private void attach_Branchies(Branchy entity)
//		{
//			this.SendPropertyChanging();
//			entity.Branchy1 = this;
//		}
		
//		private void detach_Branchies(Branchy entity)
//		{
//			this.SendPropertyChanging();
//			entity.Branchy1 = null;
//		}
		
//		private void attach_UserSections(UserSection entity)
//		{
//			this.SendPropertyChanging();
//			entity.Branchy = this;
//		}
		
//		private void detach_UserSections(UserSection entity)
//		{
//			this.SendPropertyChanging();
//			entity.Branchy = null;
//		}
		
//		private void attach_Users(User entity)
//		{
//			this.SendPropertyChanging();
//			entity.Branchy = this;
//		}
		
//		private void detach_Users(User entity)
//		{
//			this.SendPropertyChanging();
//			entity.Branchy = null;
//		}
//	}
	
//	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sections")]
//	public partial class Section : INotifyPropertyChanging, INotifyPropertyChanged
//	{
		
//		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
//		private int _ID;
		
//		private string _Name;
		
//		private int _ManagmentID;
		
//		private System.Nullable<int> _JobID;
		
//		private EntitySet<UserSection> _UserSections;
		
//    #region Extensibility Method Definitions
//    partial void OnLoaded();
//    partial void OnValidate(System.Data.Linq.ChangeAction action);
//    partial void OnCreated();
//    partial void OnIDChanging(int value);
//    partial void OnIDChanged();
//    partial void OnNameChanging(string value);
//    partial void OnNameChanged();
//    partial void OnManagmentIDChanging(int value);
//    partial void OnManagmentIDChanged();
//    partial void OnJobIDChanging(System.Nullable<int> value);
//    partial void OnJobIDChanged();
//    #endregion
		
//		public Section()
//		{
//			this._UserSections = new EntitySet<UserSection>(new Action<UserSection>(this.attach_UserSections), new Action<UserSection>(this.detach_UserSections));
//			OnCreated();
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
//		public int ID
//		{
//			get
//			{
//				return this._ID;
//			}
//			set
//			{
//				if ((this._ID != value))
//				{
//					this.OnIDChanging(value);
//					this.SendPropertyChanging();
//					this._ID = value;
//					this.SendPropertyChanged("ID");
//					this.OnIDChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
//		public string Name
//		{
//			get
//			{
//				return this._Name;
//			}
//			set
//			{
//				if ((this._Name != value))
//				{
//					this.OnNameChanging(value);
//					this.SendPropertyChanging();
//					this._Name = value;
//					this.SendPropertyChanged("Name");
//					this.OnNameChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagmentID", DbType="Int NOT NULL")]
//		public int ManagmentID
//		{
//			get
//			{
//				return this._ManagmentID;
//			}
//			set
//			{
//				if ((this._ManagmentID != value))
//				{
//					this.OnManagmentIDChanging(value);
//					this.SendPropertyChanging();
//					this._ManagmentID = value;
//					this.SendPropertyChanged("ManagmentID");
//					this.OnManagmentIDChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobID", DbType="Int")]
//		public System.Nullable<int> JobID
//		{
//			get
//			{
//				return this._JobID;
//			}
//			set
//			{
//				if ((this._JobID != value))
//				{
//					this.OnJobIDChanging(value);
//					this.SendPropertyChanging();
//					this._JobID = value;
//					this.SendPropertyChanged("JobID");
//					this.OnJobIDChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Section_UserSection", Storage="_UserSections", ThisKey="ID", OtherKey="SectionID")]
//		public EntitySet<UserSection> UserSections
//		{
//			get
//			{
//				return this._UserSections;
//			}
//			set
//			{
//				this._UserSections.Assign(value);
//			}
//		}
		
//		public event PropertyChangingEventHandler PropertyChanging;
		
//		public event PropertyChangedEventHandler PropertyChanged;
		
//		protected virtual void SendPropertyChanging()
//		{
//			if ((this.PropertyChanging != null))
//			{
//				this.PropertyChanging(this, emptyChangingEventArgs);
//			}
//		}
		
//		protected virtual void SendPropertyChanged(String propertyName)
//		{
//			if ((this.PropertyChanged != null))
//			{
//				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
//			}
//		}
		
//		private void attach_UserSections(UserSection entity)
//		{
//			this.SendPropertyChanging();
//			entity.Section = this;
//		}
		
//		private void detach_UserSections(UserSection entity)
//		{
//			this.SendPropertyChanging();
//			entity.Section = null;
//		}
//	}
	
//	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserSections")]
//	public partial class UserSection : INotifyPropertyChanging, INotifyPropertyChanged
//	{
		
//		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
//		private int _ID;
		
//		private int _UserID;
		
//		private int _SectionID;
		
//		private int _BranchID;
		
//		private System.Nullable<int> _ParentID;
		
//		private EntityRef<Branchy> _Branchy;
		
//		private EntityRef<Section> _Section;
		
//		private EntityRef<User> _User;
		
//    #region Extensibility Method Definitions
//    partial void OnLoaded();
//    partial void OnValidate(System.Data.Linq.ChangeAction action);
//    partial void OnCreated();
//    partial void OnIDChanging(int value);
//    partial void OnIDChanged();
//    partial void OnUserIDChanging(int value);
//    partial void OnUserIDChanged();
//    partial void OnSectionIDChanging(int value);
//    partial void OnSectionIDChanged();
//    partial void OnBranchIDChanging(int value);
//    partial void OnBranchIDChanged();
//    partial void OnParentIDChanging(System.Nullable<int> value);
//    partial void OnParentIDChanged();
//    #endregion
		
//		public UserSection()
//		{
//			this._Branchy = default(EntityRef<Branchy>);
//			this._Section = default(EntityRef<Section>);
//			this._User = default(EntityRef<User>);
//			OnCreated();
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
//		public int ID
//		{
//			get
//			{
//				return this._ID;
//			}
//			set
//			{
//				if ((this._ID != value))
//				{
//					this.OnIDChanging(value);
//					this.SendPropertyChanging();
//					this._ID = value;
//					this.SendPropertyChanged("ID");
//					this.OnIDChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
//		public int UserID
//		{
//			get
//			{
//				return this._UserID;
//			}
//			set
//			{
//				if ((this._UserID != value))
//				{
//					if (this._User.HasLoadedOrAssignedValue)
//					{
//						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
//					}
//					this.OnUserIDChanging(value);
//					this.SendPropertyChanging();
//					this._UserID = value;
//					this.SendPropertyChanged("UserID");
//					this.OnUserIDChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SectionID", DbType="Int NOT NULL")]
//		public int SectionID
//		{
//			get
//			{
//				return this._SectionID;
//			}
//			set
//			{
//				if ((this._SectionID != value))
//				{
//					if (this._Section.HasLoadedOrAssignedValue)
//					{
//						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
//					}
//					this.OnSectionIDChanging(value);
//					this.SendPropertyChanging();
//					this._SectionID = value;
//					this.SendPropertyChanged("SectionID");
//					this.OnSectionIDChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchID", DbType="Int NOT NULL")]
//		public int BranchID
//		{
//			get
//			{
//				return this._BranchID;
//			}
//			set
//			{
//				if ((this._BranchID != value))
//				{
//					if (this._Branchy.HasLoadedOrAssignedValue)
//					{
//						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
//					}
//					this.OnBranchIDChanging(value);
//					this.SendPropertyChanging();
//					this._BranchID = value;
//					this.SendPropertyChanged("BranchID");
//					this.OnBranchIDChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="Int")]
//		public System.Nullable<int> ParentID
//		{
//			get
//			{
//				return this._ParentID;
//			}
//			set
//			{
//				if ((this._ParentID != value))
//				{
//					this.OnParentIDChanging(value);
//					this.SendPropertyChanging();
//					this._ParentID = value;
//					this.SendPropertyChanged("ParentID");
//					this.OnParentIDChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Branchy_UserSection", Storage="_Branchy", ThisKey="BranchID", OtherKey="ID", IsForeignKey=true)]
//		public Branchy Branchy
//		{
//			get
//			{
//				return this._Branchy.Entity;
//			}
//			set
//			{
//				Branchy previousValue = this._Branchy.Entity;
//				if (((previousValue != value) 
//							|| (this._Branchy.HasLoadedOrAssignedValue == false)))
//				{
//					this.SendPropertyChanging();
//					if ((previousValue != null))
//					{
//						this._Branchy.Entity = null;
//						previousValue.UserSections.Remove(this);
//					}
//					this._Branchy.Entity = value;
//					if ((value != null))
//					{
//						value.UserSections.Add(this);
//						this._BranchID = value.ID;
//					}
//					else
//					{
//						this._BranchID = default(int);
//					}
//					this.SendPropertyChanged("Branchy");
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Section_UserSection", Storage="_Section", ThisKey="SectionID", OtherKey="ID", IsForeignKey=true)]
//		public Section Section
//		{
//			get
//			{
//				return this._Section.Entity;
//			}
//			set
//			{
//				Section previousValue = this._Section.Entity;
//				if (((previousValue != value) 
//							|| (this._Section.HasLoadedOrAssignedValue == false)))
//				{
//					this.SendPropertyChanging();
//					if ((previousValue != null))
//					{
//						this._Section.Entity = null;
//						previousValue.UserSections.Remove(this);
//					}
//					this._Section.Entity = value;
//					if ((value != null))
//					{
//						value.UserSections.Add(this);
//						this._SectionID = value.ID;
//					}
//					else
//					{
//						this._SectionID = default(int);
//					}
//					this.SendPropertyChanged("Section");
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_UserSection", Storage="_User", ThisKey="UserID", OtherKey="ID", IsForeignKey=true)]
//		public User User
//		{
//			get
//			{
//				return this._User.Entity;
//			}
//			set
//			{
//				User previousValue = this._User.Entity;
//				if (((previousValue != value) 
//							|| (this._User.HasLoadedOrAssignedValue == false)))
//				{
//					this.SendPropertyChanging();
//					if ((previousValue != null))
//					{
//						this._User.Entity = null;
//						previousValue.UserSections.Remove(this);
//					}
//					this._User.Entity = value;
//					if ((value != null))
//					{
//						value.UserSections.Add(this);
//						this._UserID = value.ID;
//					}
//					else
//					{
//						this._UserID = default(int);
//					}
//					this.SendPropertyChanged("User");
//				}
//			}
//		}
		
//		public event PropertyChangingEventHandler PropertyChanging;
		
//		public event PropertyChangedEventHandler PropertyChanged;
		
//		protected virtual void SendPropertyChanging()
//		{
//			if ((this.PropertyChanging != null))
//			{
//				this.PropertyChanging(this, emptyChangingEventArgs);
//			}
//		}
		
//		protected virtual void SendPropertyChanged(String propertyName)
//		{
//			if ((this.PropertyChanged != null))
//			{
//				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
//			}
//		}
//	}
	
//	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
//	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
//	{
		
//		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
//		private int _ID;
		
//		private string _Name;
		
//		private string _UserName;
		
//		private string _Password;
		
//		private int _BranchID;
		
//		private System.Nullable<int> _EmpID;
		
//		private bool _IsActive;
		
//		private char _UserType;
		
//		private string _OneSignalPlayerId;
		
//		private EntitySet<UserSection> _UserSections;
		
//		private EntityRef<Branchy> _Branchy;
		
//    #region Extensibility Method Definitions
//    partial void OnLoaded();
//    partial void OnValidate(System.Data.Linq.ChangeAction action);
//    partial void OnCreated();
//    partial void OnIDChanging(int value);
//    partial void OnIDChanged();
//    partial void OnNameChanging(string value);
//    partial void OnNameChanged();
//    partial void OnUserNameChanging(string value);
//    partial void OnUserNameChanged();
//    partial void OnPasswordChanging(string value);
//    partial void OnPasswordChanged();
//    partial void OnBranchIDChanging(int value);
//    partial void OnBranchIDChanged();
//    partial void OnEmpIDChanging(System.Nullable<int> value);
//    partial void OnEmpIDChanged();
//    partial void OnIsActiveChanging(bool value);
//    partial void OnIsActiveChanged();
//    partial void OnUserTypeChanging(char value);
//    partial void OnUserTypeChanged();
//    partial void OnOneSignalPlayerIdChanging(string value);
//    partial void OnOneSignalPlayerIdChanged();
//    #endregion
		
//		public User()
//		{
//			this._UserSections = new EntitySet<UserSection>(new Action<UserSection>(this.attach_UserSections), new Action<UserSection>(this.detach_UserSections));
//			this._Branchy = default(EntityRef<Branchy>);
//			OnCreated();
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
//		public int ID
//		{
//			get
//			{
//				return this._ID;
//			}
//			set
//			{
//				if ((this._ID != value))
//				{
//					this.OnIDChanging(value);
//					this.SendPropertyChanging();
//					this._ID = value;
//					this.SendPropertyChanged("ID");
//					this.OnIDChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
//		public string Name
//		{
//			get
//			{
//				return this._Name;
//			}
//			set
//			{
//				if ((this._Name != value))
//				{
//					this.OnNameChanging(value);
//					this.SendPropertyChanging();
//					this._Name = value;
//					this.SendPropertyChanged("Name");
//					this.OnNameChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
//		public string UserName
//		{
//			get
//			{
//				return this._UserName;
//			}
//			set
//			{
//				if ((this._UserName != value))
//				{
//					this.OnUserNameChanging(value);
//					this.SendPropertyChanging();
//					this._UserName = value;
//					this.SendPropertyChanged("UserName");
//					this.OnUserNameChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
//		public string Password
//		{
//			get
//			{
//				return this._Password;
//			}
//			set
//			{
//				if ((this._Password != value))
//				{
//					this.OnPasswordChanging(value);
//					this.SendPropertyChanging();
//					this._Password = value;
//					this.SendPropertyChanged("Password");
//					this.OnPasswordChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchID", DbType="Int NOT NULL")]
//		public int BranchID
//		{
//			get
//			{
//				return this._BranchID;
//			}
//			set
//			{
//				if ((this._BranchID != value))
//				{
//					if (this._Branchy.HasLoadedOrAssignedValue)
//					{
//						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
//					}
//					this.OnBranchIDChanging(value);
//					this.SendPropertyChanging();
//					this._BranchID = value;
//					this.SendPropertyChanged("BranchID");
//					this.OnBranchIDChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpID", DbType="Int")]
//		public System.Nullable<int> EmpID
//		{
//			get
//			{
//				return this._EmpID;
//			}
//			set
//			{
//				if ((this._EmpID != value))
//				{
//					this.OnEmpIDChanging(value);
//					this.SendPropertyChanging();
//					this._EmpID = value;
//					this.SendPropertyChanged("EmpID");
//					this.OnEmpIDChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
//		public bool IsActive
//		{
//			get
//			{
//				return this._IsActive;
//			}
//			set
//			{
//				if ((this._IsActive != value))
//				{
//					this.OnIsActiveChanging(value);
//					this.SendPropertyChanging();
//					this._IsActive = value;
//					this.SendPropertyChanged("IsActive");
//					this.OnIsActiveChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserType", DbType="Char(1) NOT NULL")]
//		public char UserType
//		{
//			get
//			{
//				return this._UserType;
//			}
//			set
//			{
//				if ((this._UserType != value))
//				{
//					this.OnUserTypeChanging(value);
//					this.SendPropertyChanging();
//					this._UserType = value;
//					this.SendPropertyChanged("UserType");
//					this.OnUserTypeChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OneSignalPlayerId", DbType="NVarChar(500)")]
//		public string OneSignalPlayerId
//		{
//			get
//			{
//				return this._OneSignalPlayerId;
//			}
//			set
//			{
//				if ((this._OneSignalPlayerId != value))
//				{
//					this.OnOneSignalPlayerIdChanging(value);
//					this.SendPropertyChanging();
//					this._OneSignalPlayerId = value;
//					this.SendPropertyChanged("OneSignalPlayerId");
//					this.OnOneSignalPlayerIdChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_UserSection", Storage="_UserSections", ThisKey="ID", OtherKey="UserID")]
//		public EntitySet<UserSection> UserSections
//		{
//			get
//			{
//				return this._UserSections;
//			}
//			set
//			{
//				this._UserSections.Assign(value);
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Branchy_User", Storage="_Branchy", ThisKey="BranchID", OtherKey="ID", IsForeignKey=true)]
//		public Branchy Branchy
//		{
//			get
//			{
//				return this._Branchy.Entity;
//			}
//			set
//			{
//				Branchy previousValue = this._Branchy.Entity;
//				if (((previousValue != value) 
//							|| (this._Branchy.HasLoadedOrAssignedValue == false)))
//				{
//					this.SendPropertyChanging();
//					if ((previousValue != null))
//					{
//						this._Branchy.Entity = null;
//						previousValue.Users.Remove(this);
//					}
//					this._Branchy.Entity = value;
//					if ((value != null))
//					{
//						value.Users.Add(this);
//						this._BranchID = value.ID;
//					}
//					else
//					{
//						this._BranchID = default(int);
//					}
//					this.SendPropertyChanged("Branchy");
//				}
//			}
//		}
		
//		public event PropertyChangingEventHandler PropertyChanging;
		
//		public event PropertyChangedEventHandler PropertyChanged;
		
//		protected virtual void SendPropertyChanging()
//		{
//			if ((this.PropertyChanging != null))
//			{
//				this.PropertyChanging(this, emptyChangingEventArgs);
//			}
//		}
		
//		protected virtual void SendPropertyChanged(String propertyName)
//		{
//			if ((this.PropertyChanged != null))
//			{
//				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
//			}
//		}
		
//		private void attach_UserSections(UserSection entity)
//		{
//			this.SendPropertyChanging();
//			entity.User = this;
//		}
		
//		private void detach_UserSections(UserSection entity)
//		{
//			this.SendPropertyChanging();
//			entity.User = null;
//		}
//	}
//}
//#pragma warning restore 1591
