//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusesWorkshop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;Initial Catalog=RealEstate;Persist Security Info=True;Us" +
            "er ID=saUser")]
        public string RealEstateConnectionString {
            get {
                return ((string)(this["RealEstateConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\sqlexpress;Initial Catalog=BusWorkshop;Persist Security Info=True;U" +
            "ser ID=saUser")]
        public string BusWorkshopConnectionString4 {
            get {
                return ((string)(this["BusWorkshopConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=37.216.238.122\\sqlexpress,3210;Initial Catalog=RealEstateFosha;Persis" +
            "t Security Info=True;User ID=saUser;Password=TamMzt@Getdate(2013)")]
        public string RealEstateFoshaConnectionString {
            get {
                return ((string)(this["RealEstateFoshaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SHADY\\SHADY2008new;Initial Catalog=BusWorkshop;Integrated Security=Tr" +
            "ue")]
        public string BusWorkshopConnectionString6 {
            get {
                return ((string)(this["BusWorkshopConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=softray;Initial Catalog=BusWorkshop;Persist Security Info=True;User I" +
            "D=sauser;Password=TamMzt@Getdate(2013)")]
        public string BusWorkshopConnectionString {
            get {
                return ((string)(this["BusWorkshopConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=softray;Initial Catalog=Esolerp;Persist Security Info=True;User ID=sa" +
            "user;Password=TamMzt@Getdate(2013)")]
        public string EsolerpConnectionString {
            get {
                return ((string)(this["EsolerpConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=37.216.238.122\\sqlexpress,3210;Initial Catalog=BusWorkshopFosha;Persi" +
            "st Security Info=True;User ID=saUser;Password=TamMzt@Getdate(2013)")]
        public string BusWorkshopFoshaConnectionString {
            get {
                return ((string)(this["BusWorkshopFoshaConnectionString"]));
            }
        }
    }
}
